"""Adding telegram_username colomn in users table

Revision ID: 6b07dc0c9e52
Revises: 44d4846040bf
Create Date: 2024-09-27 10:52:55.694801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b07dc0c9e52"
down_revision: Union[str, None] = "44d4846040bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_username", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_username")
    # ### end Alembic commands ###
