"""Updating telegram_id colomn in users table

Revision ID: 44d4846040bf
Revises: 1e9a54582d11
Create Date: 2024-09-18 19:35:21.677121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44d4846040bf"
down_revision: Union[str, None] = "1e9a54582d11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "telegram_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "telegram_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###
