"""Making user.role nullable

Revision ID: f70f0ce2bcb3
Revises: af48935b0a3b
Create Date: 2024-09-17 00:29:17.763558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f70f0ce2bcb3"
down_revision: Union[str, None] = "af48935b0a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(length=7), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(length=7), nullable=False)
    # ### end Alembic commands ###
